name: .NET Core

on:
  push:
    branches:
      - master
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - run: nuget pack IO.ClickSend.csproj -Build -Properties Configuration=Release -OutputDirectory out
      - run: nuget sources Add -Name "GitHub" -Source "https://nuget.pkg.github.com/ClickSend/index.json" -UserName ClickSend -Password ${{secrets.GPR_TOKEN}}
      - run: nuget push out/*.nupkg -Source GitHub
