name: .NET Core

on:
  push:
    branches:
      - master
jobs:
  publish-gpr:
    runs-on: windows-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@master
      
      - name: Install NuGet client
        uses: warrenbuckley/Setup-Nuget@v1
        
      - name: Build solution and generate NuGet package
        run: nuget pack IO.ClickSend.csproj -Build -Properties Configuration=Release -OutputDirectory out 

      - name: Install NuGet client
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Add private GitHub registry to NuGet
        run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/ClickSend/index.json -Username ClickSend -Password ${{ secrets.GPR_TOKEN }}

      - name: Push generated package to GitHub registry
        run: nuget push .\clicksend-csharp\out\*.nupkg -Source "GPR" -SkipDuplicate
      

